### ISSUE TITLE
Found X elements with non-unique id

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-multiple-custom-select-changelog#1]
When i use multiple select input in the same page it throws an error in chrome console saying "Found X elements with non-unique id".
Is there a way to set a custom id for every checkbox, cause it's generated automatically.

**Comment by omarherri** [comment]
<img width="1163" alt="Capture d’écran 2020-05-17 à 16 05 15" src="https://user-images.githubusercontent.com/12627384/82153642-488d8680-9858-11ea-9a95-681bb1065d8c.png">
this is the screenshot

**Comment by claudia-romano** [comment]
Hi Omar thanks for the heads-up. We have just fixed this issue. You can get the updated JS code from the component page:
https://codyhouse.co/ds/components/app/multiple-custom-select

If you are still having problems, feel free to reopen this issue. Cheers!
